spring:
  application:
    name: aitasks

  data:
    mongodb:
      uri: mongodb://localhost:27017/aitasksdb

gemini:
  api-key: ${GEMINI_KEY}
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"